title: Marco Doctor Portfolio
description: IT Specialist, Aspiring AI Enthusiast, and Creative Digital Content Creator
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mrcdctrportfolio.com" # the base hostname & protocol for your site
author:
  name: Marco Doctor
  email: mrcdctr@gmail.com
social:
  github: https://github.com/mrcdctr
  linkedin: https://www.linkedin.com/in/marco-doctor-ab0a57140/
  portfolio: https://www.mrcdctrportfolio.com
